### ISSUE TITLE
Swift 2

### ISSUE THREAD

**Issue by Fredehagelund92** [nicolasgomollon/PTATableViewCell#2]
Will this be updated for swift 2.0 ?

**Comment by nicolasgomollon** [comment]
Soon. I’m still working out a couple bugs that showed up after converting to the latest syntax.

**Comment by nicolasgomollon** [comment]
Looks like that took a lot less time than I thought! You can now fetch the latest commit (955ca9328707a923fbd4a5a0d9a3dc7d7139328a) from the master branch of this repo.
